{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bacondecomp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bacondecomp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bacondecomp/bacondecomp_{{ version }}.tar.gz
  sha256: f53a8477c8abc003750476e8ff42f225dce3e56a6a6f2658f97da35ee1baa6e9

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('bacondecomp')"           # [not win]
    - "\"%R%\" -e \"library('bacondecomp')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bacondecomp
  license: MIT
  summary: Decomposition for differences-in-differences with variation in treatment timing from
    Goodman-Bacon (2018) <doi:10.3386/w25018>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec

# Package: bacondecomp
# Type: Package
# Title: Goodman-Bacon Decomposition
# Version: 0.1.1
# Authors@R: c( person("Evan", "Flack", email = "evanjflack@gmail.com", role = c("aut", "cre")), person("Edward", "Jee", role = c("aut")) )
# Maintainer: Evan Flack <evanjflack@gmail.com>
# Description: Decomposition for differences-in-differences with variation in treatment timing from Goodman-Bacon (2018) <doi:10.3386/w25018>.
# License: MIT + file LICENSE
# Depends: R (>= 2.10)
# Suggests: knitr, rmarkdown, testthat, ggplot2, covr
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# Encoding: UTF-8
# LazyData: true
# NeedsCompilation: no
# Packaged: 2020-01-24 20:23:14 UTC; rstudio
# Author: Evan Flack [aut, cre], Edward Jee [aut]
# Repository: CRAN
# Date/Publication: 2020-01-24 20:40:02 UTC
